### PR TITLE
Add support for postgres UUID fields

### PR DESCRIPTION
**Pull request by quentin-fox**
Adds support for the `uuid` postgres type, using the `github.com/google/uuid` package for storing UUIDs. I think in the future, it might be worth adding in configuration in sqgen-postgres to generate uuid fields as BinaryFields or StringFields (since they can be scanned into either data type just fine), but I'm keeping the initial PR small.

Unfortunately, `database/sql` doesn't support a NullUUID type like it does for NullString, etc., so I've used the uuid.Nil (which is just a [16]byte with all 0's) to represent an "null" uuid type. I'm happy to change the implementation of null UUIDs if there's a better way to do this.

I've added a few test cases, and populated the `media` table in the postgres devlab database so we can query for a deterministic UUID in the tests.

If this PR gets accepted, I can also add the implementation for mysql and the accompanying documentation, just wanted to small start at first.

I also moved the `txdb` registration into a `func TestMain(t *testing.M) {}` block - from what I can tell, I think that's a more common practice for test setup than `init` functions.

### CODE REVIEW

**Comment by bokwoon95** [comment]
Can you change uuid.UUID to [16]byte instead, so that it also works with other uuid-compatible types like [oklog/ulid's](https://www.google.com/search?q=oklog+ulid) [ULID](https://pkg.go.dev/github.com/oklog/ulid/v2#ULID) type. If I'm not wrong using [16]byte as the argument will allow both uuid.UUID and ulid.ULID to be passed without any type conversion.

```go
func (col *Column) SetUUID(field UUIDField, value [16]byte) // allowed: SetUUID(field, uuid.UUID{})
func (r *Row) UUID(field UUIDField) [16]byte                // allowed: var id uuid.UUID; id = r.UUID(field)
func (f UUIDField) EqUUID(u [16]byte)                       // allowed: field.EqUUID(uuid.UUID{})
```

I think (*Row).ScanInto should also omit handing the *uuid.UUID type, because uuid.UUID already implements driver.Scanner. So if the user calls `var id uuid.UUID; r.ScanInto(field, &id)` it should do the right thing (idk, can you check if that's the case).

**Comment by quentin-fox** [comment]
Good call on changing it to `[16]byte` instead - I thought that the type aliasing of `[16]byte` as `uuid.UUID` would prevent the `uuid.UUID` from being used as a parameter to a function that accepts `[16]byte`, but it absolutely can be used (this was news to me, see: https://stackoverflow.com/a/19334952).

I'll double check on the `r.ScanInto` method as well. Do you think it will be necessary to add a case for `[16]byte` to (*Row).ScanInto, since it doesn't implement sql.Scanner?

Thanks for the review!

**Comment by bokwoon95** [comment]
Nah no need, the user won't ever be scanning into a [16]byte: they'll either scan into a uuid.UUID or ulid.ULID. What I'm concerned about is the driver.Valuer implementation. Because now whenever a user passes in a UUID it gets converted into a [16]byte, which no longer implements driver.Valuer. uuid.UUID apparently [converts the [16]byte into a string](https://pkg.go.dev/github.com/google/uuid#UUID.Value) before passing it to the driver, while ulid.ULID [converts it into a []byte](https://pkg.go.dev/github.com/oklog/ulid/v2#ULID.Value). Because UUIDs and ULIDs have different string formats, we can't convert them into a string. The only option is to convert it into a byte slice.

```go
func (col *Column) SetUUID(field UUIDField, value [16]byte) {
    col.Set(field, value[:])
}
```

The only problem is if the underlying driver doesn't support byte slices. I don't know which of the sql drivers don't support byte slices, but I assume most of them do considering that ulid.ULID submits itself as a byte slice to the driver.

**Comment by quentin-fox** [comment]
Makes a lot of sense. I've been able to convert over the uuid code in column.go and uuid_field.go (just pushed two new commits, with tests passing), but I'm still having some issues with the scanning in row.go.

I'm still having some odd issues with the `(*Row).UUID(field UUIDField)` method. I've converted the implementation to the following (also pushed a commit with these changes, but tests failing):

```go
// UUID returns the [16]byte value of the UUIDField
func (r *Row) UUID(field UUIDField) [16]byte {
	if r.rows == nil {
		r.fields = append(r.fields, field)
		r.dest = append(r.dest, &[]byte{})
		return [16]byte{}
	}

	uuid := r.dest[r.index].(*[]byte)

	var dest [16]byte
	copy(dest[:], *uuid)

	r.index++
	return dest
}
```

This works without any runtime errors when running the queries, but database driver isn't scanning into the []byte correctly.

The UUID in the media table in the database is hardcoded as the string "dbc59321-22ee-4613-bb27-8b2ba5be3109". Instead of scanning the byte representation of the uuid value into the `[]byte` destination, it's scanning `[]byte("dbc59321-22ee-4613-bb27-8b2ba5be3109")`, which ends up being much longer than 16 bytes - so when copying the uuid into the dest `[16]byte`, it only copies the first 16 bytes. Obviously this leads to incorrect outputs.

Is there a solution that's immediately obvious to you? I'm not sure if there's a simple way to handle a driver scanning a UUID as a string - if we look at the implementation in `github.com/google/uuid`, in the `(*UUID).Scan(src {}interface)` method both the `string` case and the `[]byte` case are explicitly handled. Short of simply re-implementing the uuid.Parse function here (which is seriously not the right approach), is there a way around this that makes sense?

**Comment by bokwoon95** [comment]
lol this is an unexpected brick wall. Further testing shows that even BYTEA cannot be casted to UUID (`SELECT CAST(CAST('\xdbc5932122ee4613bb278b2ba5be3109' AS BYTEA) AS UUID);`). It seems like the postgres UUID presents itself exclusively as a string to the outside world, and only works as a 16-byte value internally.
If that's the case we have to go all-in on UUIDs (and the UUID string format) and give up compatibility with other [16]byte types.

There may still be some value in preserving [16]byte as the method type argument though. There are other UUID packages out there like [github.com/satori/go.uuid](github.com/satori/go.uuid) which are also backed by a [16]byte. Externally we can accept a [16]byte but internally we convert the [16]byte into a uuid.UUID so that we can can leverage its ability to marshal to and unmarshal from a UUID string. That way other UUID packages should be able to interoperate with the UUIDField as normal.

**Comment by quentin-fox** [comment]
Definitely agree on preserving the external [16]byte method and return types. I wonder if there would be value in writing both a (*Row).UUID and a (*Row).ULID function, and using the google/uuid or oklog/ulid types respectively as the internal `dest`. I don't think that the UUID and ULID formats are compatible, so if we scan a ULID (from a uuid column) in Postgres into a uuid.UUID type internally, and return a [16]byte, that may not be a valid ULID?

I would imagine that different UUIID libraries would parse string uuids to the exact same [16]byte representation, and similarly for any ULID libraries, so it would be sufficient to offer just those two functions, since they're returning [16]byte in both cases. In other words, we wouldn't need to create a (*Row).UUID that uses satori/go.uuid under the hood.

Thoughts? I think while it's not a super clean solution like we hoped, I think it's about as good as we might be able to get.

**Comment by bokwoon95** [comment]
Now that I think about it there's no need to support ULID specially because it will usually be stored in the database as a BYTEA/BLOB/BINARY(16) -- that's represented by a BinaryField. The user can convert the uuid.ULID to and from a byte slice in order to make it work with BinaryField.

```go
// not yet implemented, but reasonable to add
func (col *Column) SetBytes(field BinaryField, value []byte) // usage: col.SetBytes(field, ulid[:])
// not yet implemented, but reasonable to add. The reason why a Field is used
// over a BinaryField is because anything returned by the driver can be scanned
// into a byte slice (that's what sql.RawBytes does). Having to use
// copy(ulid[:], b) is not ideal, but we can think about a better way in the
// future when people complain about it. I don't know how widespread ULID is.
func (r *Row) Bytes(field Field) []byte          // usage: b := r.Bytes(field); copy(ulid[:], b)
func (f BinaryField) EqBytes(b []byte) Predicate // usage: f.EqBytes(ulid[:])
```

> I don't think that the UUID and ULID formats are compatible, so if we scan a ULID (from a uuid column) in Postgres into a uuid.UUID type internally, and return a [16]byte, that may not be a valid ULID?

I actually don't think it is possible to store a ULID in a UUID column at all. Postgres really just flat out refuses to store arbitrary bytes in a UUID column, the only way you're getting data in and out of a UUID column is via UUID strings. And as already mentioned ULID strings are totally incompatible with UUID strings.

> In other words, we wouldn't need to create a (*Row).UUID that uses satori/go.uuid under the hood.

Yeah no need to use satori/go.uuid. As long as we have a library for converting between UUID [16]byte and UUID string (which we're using google/uuid for) it doesn't matter which UUID type the user uses as long as it follows the string format.

**Comment by quentin-fox** [comment]
Awesome, just pushed a commit that uses google/uuid internally for scanning. Missed your comment about ULIDs, but I just reverted that commit.

Do you think there's anything else we need to tweak? It would be great if you could tag a new version of the library if this PR is merged 😃

**Comment by quentin-fox** [comment]
I've fixed those issues by just using the uuid.UUID internally everywhere for all values and dests, rather than trying to mess with the conversion of `[]byte` values in the `appendSQLValue` function here:

https://github.com/quentin-fox/go-structured-query/blob/81826a4fa3529f1d5b35c5c391744c074c1b2393/postgres/string_util.go#L54-L68

**Comment by bokwoon95** [comment]
> It seems to be interpolating all of the items in the []byte slice in the UUIDField into separate $1, $2... etc. placeholders.

That's a bug on my end... appendSQLValue is supposed to expand all slices -except- byte slices. You've discovered a way around it by using uuid.UUID internally, but I'll write a fix to exclude byte slices from appendSQLValue.

**Comment by quentin-fox** [comment]
I made a modification to the appendSQLValue as well, but I was running into issues where the Postgres driver wasn't accepting the []byte slices properly, as it was returning the following error:

`pq: invalid byte sequence for encoding "UTF8": 0xaf`

The args for the query were:

`[[]byte{28 131 16 46 139 126 72 150 128 103 44 68 165 46 87 84}]`

which was a valid uuid, cast to a `[]byte`.

That's why I used the uuid.UUID internally, since the uuid converts the [16]byte to a string in the Valuer method.

**Pull request merged**
